### PR TITLE
Support for SpringBoot 3

### PR DESCRIPTION
**Pull request by chriseteka**
This PR hopes to answer to the issue: #62, and since I use it in one of my projects, I thought I help a little.

I am not so sure what the process of contributing to this repo is like. However, I have made some few changes on a forked copy of the repo, I have also run through all the test files and ensure nothing was failing.

Please have a look at this PR, make changes where you see fit, or add comments (I can have a look at it later in the week).
If there are other requirements needed from me, please share. It would also be helpful if there is a CONTRIBUTING.md file that outline the contributing processes, and also mentions things like how to compile, test and verify that the changes matches all criteria and is fit to be merged.

Thank you guys for the good work.

### CODE REVIEW

**Comment by alvistar** [comment]
Hello,
I am interested in this as well.

I tried to compile your fork but I have some error messages anyway in mvn clean install.
I am using openjdk 17.0.2

ommon: Compilation failure: Compilation failure:
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QDesignProject
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QUserRole
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QLocalTag
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QProject
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QAdminProject
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QUser
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QTrunk
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QProjectTag
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QRole
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QTrunkGroup
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QCompany
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QSite
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QCity
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QUserRole_UserRolePK
[ERROR] Attempt to recreate a file for type io.github.perplexhub.rsql.model.QBigTag

**Comment by chriseteka** [comment]
Hi @alvistar 
Yeah, something strange going on. I traced it down to the plugin `querydsl-apt` in the commons module. I'm not sure why it's failing, but I am trying to understand what it does and how. I'll update PR once I fix it.

**Comment by chriseteka** [comment]
Hi @perplexhub 
mind having a look at this?
Thanks.

**Comment by perplexhub** [comment]
Hi @chriseteka , thanks for your contribution. Your PR looks great.
Could you take a look about the PR build? Those test cases are not run actually. Thanks.
https://github.com/perplexhub/rsql-jpa-specification/actions/runs/3748404566/jobs/6368298850

Since this is a big change, could I leave this PR open for awhile to see any further comments from other users and contributors?

**Comment by chriseteka** [comment]
Hi @perplexhub 
Thanks for having a look. It's fine to leave it open for some time so that others can have a look as well.

**Comment by sinanyumak** [comment]
Hi @chriseteka 

Your pull request looks good. Thanks :) Hope it gets merged soon.

**Comment by perplexhub** [comment]
The PR was merged and version 6.0.2 was released.
@chriseteka Thanks again for your contribution.

**Pull request merged**
