### PR TITLE
Optional ManyToOne association

### PR DESCRIPTION
**Pull request by Almalerik**
ManyToOne association is always inner join but in some case could be optional.
I added a method to read optional attribute from ManyToOne and OneToOne association to make a choice between left join and inner join.
Thanks for this great starter.

### CODE REVIEW

**Review by perplexhub — APPROVED** [review]

**Comment by nickcaballero** [comment]
This actually changes the semantics for people already querying on these relationships. Might want to add some release notes or something indicating that this may be a breaking change.

**Comment by Almalerik** [comment]
Why do you think that? If optional attribuite is not set or is false the semantic is the same; if optional is true with prev version a inner join was used loosing data on null join.
Perhaps I can't figure out the problem.

**Comment by nickcaballero** [comment]
The left join may include data that was previously excluded. Unless the where clause was already excluding the data, the result may have records that were not supposed to be there. Consider a null check on a column - previously the joined rows that had a null value would have been included. Now, both rows with a null value and rows that were missing would be included.

**Comment by perplexhub** [comment]
I reverted the merge first. We better come up a solution which will not impact the existing usage.

**Comment by Almalerik** [comment]
Not a problem but original code always sets a left join in onetoone or onetomany relationships otherwise it is an inner join.
Manytoone should also be a left join because from JPA specifications it’s default optional true.
Actual code loses this data with a wrong join (with no way to get them) but the correct thing is to include them and use where clause to exclude it.
Uses a “limitation” of the code (I don't mean it's wrong :) related to the choice of relations is not a good reason to write wrong sql code.
My changes only effects in manytoone relations and preserves a inner join when optional is false.

**Comment by Almalerik** [comment]
however, thinking about it, I can try to add a property in order to enable or disable the use of the optional attribute for a backward compatibility

**Comment by Gray557** [comment]
Hi! I faced with a similar issue:
Due to using inner join instead of left join, I received not full values from DB.

Example: 
I have elements with types with possible values: Region, City, Street 
And also this object has fields: parentArea and childArea where these elements connecting each over by id.

For example, I have 2 values in DB: 
1val: 
id: 1
type: Region
childArea: 2
parentArea: null.

2 val: 
id: 2
type: City
parentArea: 
       id: 1
       type: Region
childArea: anyElementNotImportant

In case of :  search=type==Region,parentArea.type==Region -> I will not recieve first element cause parentArea is null.
So, please make a special version/release/config to choose left join.

**Pull request merged**
